### ISSUE TITLE
无法对axios实例添加拦截器

### ISSUE THREAD

**Issue by topit** [libaoxu/axios-service#1]
由于使用了内容axios.create()创建实例，外部全局的axios拦截器，无法作用域内部实例。
example: https://runkit.com/embed/k04bt2wv3t5c
希望添加拦截器支持

Context:
axios@0.16.2
axios-service@1.0.7

**Comment by libaoxu** [comment]
是因为创建实例过多引起, 已修改创建实例方式, 跟下面问题是相同原因引起, 谢谢指正
Duplicate of #2
