### ISSUE TITLE
创建了太多的实例

### ISSUE THREAD

**Issue by topit** [libaoxu/axios-service#2]
对于每次请求，createInstance都创建了一个实例，导致创建了太多的实例。

src/index.js
```js
const createInstance = function createInstance (requestOpts) {
    clearTimeout(tid)
    let instance = service.$http.create({
      baseURL: root,
      ...baseConfigs
    })
    instance.baseURL = root
    return _request = getWrapperRequest(instance)(requestOpts)
  }
```
另外，最好能支持到处实例，就能做些自定义配置。

Context:
axios@0.16.2
axios-service@1.0.7

**Comment by libaoxu** [comment]
已暴露每次创建的axiosInstance对象,
[代码](https://github.com/libaoxu/axios-service/commit/8bf71a0edbd1223ec43e1c0c71525f2727dec391#diff-1fdf421c05c1140f6d71444ea2b27638R171)

并且只有当getRequestsByRoot传入参数isCreateInstance时, 才会调用axios.create, 默认调用全局axios
[更新日志](https://github.com/libaoxu/axios-service/blob/master/changelog.md#110)
[使用示例](https://github.com/libaoxu/axios-service#apis%E9%85%8D%E7%BD%AE)
