### ISSUE TITLE
消息装饰圈 文档单词拼写 有误

### ISSUE THREAD

**Issue by huangjincq** [libaoxu/axios-service#5]
### 中 getMesageDecorator  =》 getMessageDecorator
import { getMesageDecorator } from 'axios-service'

### sucessMsg=》successMsg
getInfoFunc: compose(
    messageDecorator({ sucessMsg: '请求成功', errorMsg: (error) => (error && error.msg) || '请求失败' })
    mockSuccess
  )(get('api/getInfo'))

**Comment by libaoxu** [comment]
谢谢指正, 可以写一下代码的详细位置

**Comment by libaoxu** [comment]
已更新 [消息装饰器文档说明](https://github.com/libaoxu/axios-service#%E6%B6%88%E6%81%AF%E8%A3%85%E9%A5%B0%E5%99%A8)
