### ISSUE TITLE
当返回值不是json时 会报错

### ISSUE THREAD

**Issue by songjiafan** [libaoxu/axios-service#7]
<img width="518" alt="屏幕快照 2019-07-17 18 54 50" src="https://user-images.githubusercontent.com/22863991/61370268-96e29980-a8c4-11e9-8455-e312921198bf.png">
<img width="535" alt="屏幕快照 2019-07-17 18 55 15" src="https://user-images.githubusercontent.com/22863991/61370275-9a762080-a8c4-11e9-8635-85297fa344e7.png">

不知道需不需要兼容这种情况

**Comment by libaoxu** [comment]
ok, 这个需要考虑一下, 至少不报错, 还给返回出去, 线上接口有这种场景?

**Comment by libaoxu** [comment]
> <img alt="屏幕快照 2019-07-17 18 54 50" width="518" src="https://user-images.githubusercontent.com/22863991/61370268-96e29980-a8c4-11e9-8455-e312921198bf.png">
> 
> <img alt="屏幕快照 2019-07-17 18 55 15" width="535" src="https://user-images.githubusercontent.com/22863991/61370275-9a762080-a8c4-11e9-8635-85297fa344e7.png">
> 
> 不知道需不需要兼容这种情况

ok, 这个需要考虑一下, 至少不报错, 还给返回出去, 线上接口有这种场景?

**Comment by songjiafan** [comment]
这个是接口在测试的时候后端在调试的时候发现的 但是考虑到接口返回数据也不一定非得是json的情况 可能需要处理一下

**Comment by libaoxu** [comment]
dataKey不传的时候, 就不处理了, 会将http请求中data字段全部返回, 就可以满足服务端不返回json的情况, 参考
 [全局配置示例](https://github.com/libaoxu/axios-service#%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AE)
[配置参考示例](https://github.com/libaoxu/axios-service/blob/master/examples/client/apis.js#L15)
[dataKey处理源码](https://github.com/libaoxu/axios-service/blob/master/src/create.js#L49)
