### ISSUE TITLE
getMessageDecorator 接口提示装饰器，this 指向报错

### ISSUE THREAD

**Issue by qiuyeduxin** [libaoxu/axios-service#8]
**问题**：当传进去的message组件是来之ivew时候，调用message.success会找不到 this,如下图：
![image](https://user-images.githubusercontent.com/10897871/66728502-e90d6980-ee77-11e9-9b7a-cf4a57b3e41a.png)
然后浏览器会报错，找不到this
![image](https://user-images.githubusercontent.com/10897871/66728531-1823db00-ee78-11e9-8015-c577e8a33760.png)

**解决方法：**
在axios-service项目中 src/service-decorators.js 文件里，找到getMessageDecorator这个方法，找到getToast这个方法，给toast[name] 加上bind(toast)，如下图
![image](https://user-images.githubusercontent.com/10897871/66728567-57eac280-ee78-11e9-903a-c6a0a8a75952.png)

**Comment by libaoxu** [comment]
问题很不错 值得修复

**Comment by libaoxu** [comment]
> **问题**：当传进去的message组件是来之ivew时候，调用message.success会找不到 this,如下图：
> ![image](https://user-images.githubusercontent.com/10897871/66728502-e90d6980-ee77-11e9-9b7a-cf4a57b3e41a.png)
> 然后浏览器会报错，找不到this
> ![image](https://user-images.githubusercontent.com/10897871/66728531-1823db00-ee78-11e9-8015-c577e8a33760.png)
> 
> **解决方法：**
> 在axios-service项目中 src/service-decorators.js 文件里，找到getMessageDecorator这个方法，找到getToast这个方法，给toast[name] 加上bind(toast)，如下图
> ![image](https://user-images.githubusercontent.com/10897871/66728567-57eac280-ee78-11e9-903a-c6a0a8a75952.png)
问题很不错 值得修复
